shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/common-aliases/*.zsh", "plugins/git/*.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]
