# Colors (Monokai Pro)
[colors.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.normal]
black = "#403E41"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.primary]
background = "#2D2A2E"
foreground = "#FCFCFA"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "ZUTOMOJI_HG35C"

[scrolling]
history = 20000

[shell]
args = ["--login"]
program = "zsh"

[window]
option_as_alt = "Both"
