# Colors (Monokai Pro)
[colors.bright]
black = "#7F8490"
blue = "#F39660"
cyan = "#76CCE0"
green = "#9ED072"
magenta = "#B39DF3"
red = "#FC5D7C"
white = "#E2E2E3"
yellow = "#E7C664"

[colors.normal]
black = "#181819"
blue = "#F39660"
cyan = "#76CCE0"
green = "#9ED072"
magenta = "#B39DF3"
red = "#FC5D7C"
white = "#E2E2E3"
yellow = "#E7C664"

[colors.primary]
background = "#2C2E34"
foreground = "#E2E2E3"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "ZUTOMOJI_HG35C"

[scrolling]
history = 20000

[shell]
args = ["--login"]
program = "zsh"

[window]
option_as_alt = "Both"
