[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  if (has("termguicolors"))
   set termguicolors
  endif
  
  let g:lightline = { 'colorscheme': 'tender' }
  
  colorscheme tender
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = false
rev = 'release'
hook_add = '''
  :nmap <space>e <Cmd>CocCommand explorer<CR>
'''
