[tools]
actionlint = "latest"
cspell = "latest"
"gem:rubocop" = "latest"
"gem:slim_lint" = "latest"
"gem:steep" = "latest"
hadolint = "latest"
lefthook = "latest"
node = "latest"
"npm:@playwright/cli" = "latest"
"npm:ccstatusline" = "latest"
"npm:ccusage" = "latest"
"npm:difit" = "latest"
"npm:eslint" = "latest"
"npm:kanban" = "latest"
"npm:prettier" = "latest"
"npm:vibe-kanban" = "latest"
pinact = "latest"
python = "latest"
ruby = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tombi = "latest"
yamlfmt = "latest"
